/**
 * The bundled registry data, generated by scripts/build-data.mjs from
 * mzizi-registry at the ref pinned in scripts/registry-ref.json. Nothing here is
 * fetched at request time and nothing comes from a database.
 */
import componentsJson from "./data/components.json";
import sourcesJson from "./data/sources.json";
import helixJson from "./data/helix.json";
import changelogJson from "./data/changelog.json";
import doctrineJson from "./data/doctrine.json";
import skillsJson from "./data/skills.json";
import samplesJson from "./data/samples.json";
import brandJson from "./data/brand.json";
import metaJson from "./data/meta.json";
import componentDocsJson from "./data/component-docs.json";
import aiInstructionIndexJson from "./data/ai-instruction-index.json";

// The generated JSON is typed loosely on purpose: its shape is mzizi-registry's
// (lib/registry.ts `RegistryItem`, lib/db/types.ts rows), and the parity script
// — not a second copy of those types — is what holds this Worker to it.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Loose = any;

export interface RegistryItem {
  name: string;
  type?: string;
  title?: string;
  description?: string;
  author?: string;
  categories?: string[];
  docs?: string;
  dependencies?: string[];
  registryDependencies?: string[];
  files?: Array<{ path: string; type: string; target?: string }>;
  meta?: { owner?: string; collection?: string } & Record<string, unknown>;
  node?: number;
  nodeLabel?: string;
  cssVars?: Loose;
  css?: Loose;
  style?: Loose;
  iconLibrary?: Loose;
  baseColor?: Loose;
  tailwind?: Loose;
  /** `sources.rs` from the registry's on-disk index, when the item has a Dioxus file. */
  rsPath?: string;
  /** mzizi-registry `crateFor(rsPath)`: the crate that compiles the `.rs`, when there is one. */
  rsCrate?: string | null;
}

export const components = componentsJson as unknown as RegistryItem[];
const byName = new Map(components.map((c) => [c.name, c]));

export const renames = metaJson.renames as Record<string, string>;
export const openapiYaml: string = metaJson.openapiYaml;
/** mzizi-registry `CRATE_GIT`: the git install for every Roots crate, on `/v1/rs/{name}`. */
export const crateGit: string = metaJson.crateGit;

/** lib/registry.ts `readComponent`: by name, then by the name it was renamed from. */
export function readComponent(name: string): RegistryItem | null {
  const found = byName.get(name);
  if (found) return found;
  const current = Object.prototype.hasOwnProperty.call(renames, name)
    ? renames[name]
    : undefined;
  return current ? (byName.get(current) ?? null) : null;
}

const sources = sourcesJson as Record<
  string,
  { primary: string | null; rs: string | null }
>;
/** lib/registry-source.ts `readComponentSource` / `readComponentSourceFor(name, "rs")`. */
export const readSource = (
  name: string,
  kind: "primary" | "rs",
): string | null => sources[name]?.[kind] ?? null;

export const helix = helixJson.model as Loose as {
  nodes: Array<{ node_number: number } & Record<string, unknown>>;
  rungs: Array<{ node_number: number } & Record<string, unknown>>;
  strands: Array<Record<string, unknown>>;
};
export const nodeCounts = helixJson.nodeCounts as Record<string, number>;

export const changelog = changelogJson as Loose as {
  entries: Array<Record<string, unknown>>;
  byVersion: Record<string, Array<Record<string, unknown>>>;
};

export const doctrine = doctrineJson as Loose as Record<string, Loose>;
export const skills = skillsJson as Loose as {
  list: unknown[];
  byName: Record<string, unknown>;
  names: string[];
  version: string;
};
export const samples = samplesJson as Loose as Record<string, unknown[]>;
export const brand = brandJson as Loose;

/**
 * lib/db `getComponentWithDocs(name)` → `{ docs, demo }`, per component: the docs
 * row (use cases, variants, sizes, features, a11y, examples) and the demo flag,
 * built from each item's `meta` block in registry.json.
 */
const componentDocs = componentDocsJson as Loose as Record<
  string,
  { docs: unknown; demo: unknown }
>;
export const readComponentDocs = (
  name: string,
): { docs: unknown; demo: unknown } | null =>
  Object.prototype.hasOwnProperty.call(componentDocs, name)
    ? componentDocs[name]
    : null;

const aiInstructionIndex = aiInstructionIndexJson as Record<string, number>;
/**
 * lib/db `getAiInstruction(key) ?? getAiInstructionByTarget(key)`: an instruction
 * set by name, else by target, or null.
 */
export function readAiInstruction(key: string): Record<string, unknown> | null {
  if (!Object.prototype.hasOwnProperty.call(aiInstructionIndex, key))
    return null;
  return (doctrine.aiInstructions as Array<Record<string, unknown>>)[
    aiInstructionIndex[key]
  ];
}
